### ISSUE TITLE
Delete An AO from this list  - Enhancement

### ISSUE THREAD

**Issue by victorSauceda** [evanpetzoldt/qsignups-lambda#46] opened 2023-03-29 15:02 UTC
Should be able to delete an ao from the list. Currently seems like it can only edit the AO but not delete from the list completely. Was able to remove it as a recurring event but would still like to move it off the list.

**Comment by evanpetzoldt** [comment] 2023-03-29 15:15
Thanks, but duplicate of #7

**Closed by evanpetzoldt** 2023-03-29 15:15 UTC
Labels: duplicate
